import type { Metadata } from "next";
// import localFont from 'next/font/local'
import Sidebar from "../components/sidebar"
import Header from "@/components/header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const swiss = localFont({ src: '../../public/fonts/Swiss 721 BT.woff' })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen font-sans`}>
        <Header/>
        <div className={`flex flex-col md:flex-row w-screen`}>
          <Sidebar/>
          <main className="flex-1 p-4 w-[100%] max-w-screen-xl mx-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
